apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: quay.io/dsanchor/quarkus-petclinic
  newName: image-registry.openshift-image-registry.svc.cluster.local:5000/gorkajimeno/quarkus-petclinic
  newTag: 92f9a2a0f6bb83a1b0eb40d66850b6d126442269
